### ISSUE TITLE
Notifications Still Showing

### ISSUE THREAD

**Issue by unparted** [BedWarMod/BedWar#1]
I have turned off all of the notifications, but it still says when I get a kill as a notification. I have looked through the settings many times, even disabling everything, but they still show. Is there a way to turn this off or is this a bug?

**Comment by CalMWolfs** [comment]
It's probably a bug. I'll look into it and get a release out in the next day

**Comment by CalMWolfs** [comment]
Just fixed it and released version 0.1.5 Let me know if it is working there but it should be. You just need to disable game notifications

**Comment by unparted** [comment]
Ight I will check it out soon, thanks. I was also wondering if I could suggest a feature. I would like to be notified when my teammates die using the notifications feature, so I know if there is anybody protecting my base or not. Do you think this would be possible to add? Thanks for your time.

**Comment by unparted** [comment]
The bug is fixed, thanks.

**Comment by CalMWolfs** [comment]
> Ight I will check it out soon, thanks. I was also wondering if I could suggest a feature. I would like to be notified when my teammates die using the notifications feature, so I know if there is anybody protecting my base or not. Do you think this would be possible to add? Thanks for your time.

Right now there is no notifications for this but the team status display does show your teammates health and also a respawn timer. Is this enough or would you like more functionality on top of this?

**Comment by mengzhu3261** [comment]
```
BedWar Mod 0.1.5: Api error
 
Caused by kotlin.collections.builders.ListBuilder: Connect to bedwar-mod.cwolfson58.workers.dev:443 [bedwar-mod.cwolfson58.workers.dev/31.13.75.5] failed: Connection timed out: connect
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at BW.utils.ApiUtils.getJSONResponse(ApiUtils.kt:64)
	at BW.utils.ApiUtils.access$getJSONResponse(ApiUtils.kt:20)
	at BW.utils.ApiUtils$getBedwarsStats$result$1.invokeSuspend(ApiUtils.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by kotlin.collections.builders.ListBuilder: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:239)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
```

**Comment by mengzhu3261** [comment]
There is an error with your MOD. I can't query my own results in the single player world and the server is unavailable
The last version worked

**Comment by CalMWolfs** [comment]
> There is an error with your MOD. I can't query my own results in the single player world and the server is unavailable The last version worked

Hi, I have tried to recreate this issue but i cannot. It seems to be working for others. Is there any chance that cloudflare is blocking your request.
Or if you can provide more steps for me to try and reproduce the error

**Comment by mengzhu3261** [comment]
My God, author, your reply is so fast, I have been testing your MOD all afternoon today, I think the reason may be because I am in China, can you add my dis? I can give you screenshots and more crash reporMts

**Comment by mengzhu3261** [comment]
> > There is an error with your MOD. I can't query my own results in the single player world and the server is unavailable The last version worked
> 
> Hi, I have tried to recreate this issue but i cannot. It seems to be working for others. Is there any chance that cloudflare is blocking your request. Or if you can provide more steps for me to try and reproduce the error

Author If you read it, reply to me. Thank you

**Comment by mengzhu3261** [comment]
my dis ID is mengzhuchina

**Comment by mengzhu3261** [comment]
![7OB%RIM JDE 913I~FE_PVJ](https://github.com/BedWarMod/BedWar/assets/147975362/59ce987c-300e-4b3c-9ea2-6d9bd898c801)

**Comment by mengzhu3261** [comment]
```
BedWar Mod 0.1.5: Api error
 
Caused by kotlin.collections.builders.ListBuilder: Connect to bedwar-mod.cwolfson58.workers.dev:443 [bedwar-mod.cwolfson58.workers.dev/199.59.148.6] failed: Connection timed out: connect
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at BW.utils.ApiUtils.getJSONResponse(ApiUtils.kt:64)
	at BW.utils.ApiUtils.access$getJSONResponse(ApiUtils.kt:20)
	at BW.utils.ApiUtils$getBedwarsStats$result$1.invokeSuspend(ApiUtils.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by kotlin.collections.builders.ListBuilder: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:239)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
```

**Comment by mengzhu3261** [comment]
I don't know why this MOD won't work on my computer, but the previous version of the MOD still works

**Comment by CalMWolfs** [comment]
Unfortunately this does sound like it could be some issue due to you being in china, for now use an older version, if you want to send me something else my discord is: calmwolfs

**Comment by mengzhu3261** [comment]
> 不幸的是，这听起来确实可能是一些问题，因为你在中国，现在使用旧版本，如果你想给我发送其他东西，我的不和谐是：calmwolfs

Author I added your friend, you agree

**Comment by unparted** [comment]
> > Ight I will check it out soon, thanks. I was also wondering if I could suggest a feature. I would like to be notified when my teammates die using the notifications feature, so I know if there is anybody protecting my base or not. Do you think this would be possible to add? Thanks for your time.
> 
> Right now there is no notifications for this but the team status display does show your teammates health and also a respawn timer. Is this enough or would you like more functionality on top of this?

I would like to see a "Time since Respawn" timer or something like that on the team status display. Do you think you could possibly add this? Maybe just counts until a certain number like 10 seconds then disappears, because by that point they would have left base. Or back to my old suggestion with the death notification. I would really like to see one of these, and with my experience with programming, I would assume that the notification would be easier. So yea, I would really like some more functionality like a teammate death notification. If not, its still a great mod and I will keep using it. Thanks again.

**Comment by unparted** [comment]
> ![7OB%RIM JDE 913I~FE_PVJ](https://user-images.githubusercontent.com/147975362/282294651-59ce987c-300e-4b3c-9ea2-6d9bd898c801.png)

I also had the same issue, but I use an overlay instead so I did not require it. What I would try to do is check if you can use your web browser to access the Hypixel API. Then generate a Hypixel API key at their Developer Portal: https://developer.hypixel.net/ and input your generated API key into the mod. Pretty sure you can paste your API key in the mod.

**Comment by CalMWolfs** [comment]
> > > Ight I will check it out soon, thanks. I was also wondering if I could suggest a feature. I would like to be notified when my teammates die using the notifications feature, so I know if there is anybody protecting my base or not. Do you think this would be possible to add? Thanks for your time.
> > 
> > 
> > Right now there is no notifications for this but the team status display does show your teammates health and also a respawn timer. Is this enough or would you like more functionality on top of this?
> 
> I would like to see a "Time since Respawn" timer or something like that on the team status display. Do you think you could possibly add this? Maybe just counts until a certain number like 10 seconds then disappears, because by that point they would have left base. Or back to my old suggestion with the death notification. I would really like to see one of these, and with my experience with programming, I would assume that the notification would be easier. So yea, I would really like some more functionality like a teammate death notification. If not, its still a great mod and I will keep using it. Thanks again.

Would you like the death notifications as a separate feature to the team kill/final/bed ones?

**Comment by CalMWolfs** [comment]
> > ![7OB%RIM JDE 913I~FE_PVJ](https://user-images.githubusercontent.com/147975362/282294651-59ce987c-300e-4b3c-9ea2-6d9bd898c801.png)
> 
> I also had the same issue, but I use an overlay instead so I did not require it. What I would try to do is check if you can use your web browser to access the Hypixel API. Then generate a Hypixel API key at their Developer Portal: https://developer.hypixel.net/ and input your generated API key into the mod. Pretty sure you can paste your API key in the mod.

I switched to a new system that doesn't require personal API keys but it seems that China blocks cloudflare so that's what their issue is

**Comment by unparted** [comment]
> > > > Ight I will check it out soon, thanks. I was also wondering if I could suggest a feature. I would like to be notified when my teammates die using the notifications feature, so I know if there is anybody protecting my base or not. Do you think this would be possible to add? Thanks for your time.
> > > 
> > > 
> > > Right now there is no notifications for this but the team status display does show your teammates health and also a respawn timer. Is this enough or would you like more functionality on top of this?
> > 
> > 
> > I would like to see a "Time since Respawn" timer or something like that on the team status display. Do you think you could possibly add this? Maybe just counts until a certain number like 10 seconds then disappears, because by that point they would have left base. Or back to my old suggestion with the death notification. I would really like to see one of these, and with my experience with programming, I would assume that the notification would be easier. So yea, I would really like some more functionality like a teammate death notification. If not, its still a great mod and I will keep using it. Thanks again.
> 
> Would you like the death notifications as a separate feature to the team kill/final/bed ones?

Yea that would be awesome. Because sometimes I would like to see just the deaths, thanks.

**Comment by unparted** [comment]
> > > ![7OB%RIM JDE 913I~FE_PVJ](https://user-images.githubusercontent.com/147975362/282294651-59ce987c-300e-4b3c-9ea2-6d9bd898c801.png)
> > 
> > 
> > I also had the same issue, but I use an overlay instead so I did not require it. What I would try to do is check if you can use your web browser to access the Hypixel API. Then generate a Hypixel API key at their Developer Portal: https://developer.hypixel.net/ and input your generated API key into the mod. Pretty sure you can paste your API key in the mod.
> 
> I switched to a new system that doesn't require personal API keys but it seems that China blocks cloudflare so that's what their issue is

Yea, but can you still input a different API key in the older versions of the mods?

**Comment by CalMWolfs** [comment]
> Yea, but can you still input a different API key in the older versions of the mod right?

yeah that's the current solution until i make a new version that adds the ability to still use the old system

**Comment by mengzhu3261** [comment]
> > 是的，但是您仍然可以在旧版本的 mod 中输入不同的 API 密钥吗？
> 
> 是的，这是当前的解决方案，直到我制作一个新版本，该版本增加了仍然使用旧系统的能力
I have a new idea at the beginning of the game to detect all players within a radius of 30 squares based on their own resource pool. When there is no teammate in this range, it will automatically remind you that there is no one at home, and other teams will remind you that there are people at home.

**Comment by mengzhu3261** [comment]
> 我很快就会检查出来，谢谢。我也想知道我是否可以提出一个功能。我希望在我的队友死亡时使用通知功能收到通知，这样我就知道是否有人在保护我的基地。你认为这可以添加吗？感谢您抽出时间接受采访。

Brother, what do you think of my idea, qwq

**Comment by unparted** [comment]
> > > 是的，但是您仍然可以在旧版本的 mod 中输入不同的 API 密钥吗？
> > 
> > 
> > 是的，这是当前的解决方案，直到我制作一个新版本，该版本增加了仍然使用旧系统的能力
> > I have a new idea at the beginning of the game to detect all players within a radius of 30 squares based on their own resource pool. When there is no teammate in this range, it will automatically remind you that there is no one at home, and other teams will remind you that there are people at home.

That's considered a cheat.

**Comment by mengzhu3261** [comment]
Yes, but I think detecting the arrival of players from other teams is a gray area, which can be interpreted as a "free trap".

**Comment by unparted** [comment]
yea i agree, its definitely a gray area

**Comment by unparted** [comment]
but i think its still cheats as it is giving an advantage of awareness, similar to ESP

**Comment by mengzhu3261** [comment]
> > > > 是的，但是您仍然可以在旧版本的 mod 中输入不同的 API 密钥吗？
> > > 
> > > 
> > > 是的，这是当前的解决方案，直到我制作一个新版本，该版本增加了仍然使用旧系统的能力 我在游戏开始时有一个新想法，根据他们自己的资源池检测 30 个方格半径内的所有玩家。当这个范围内没有队友时，它会自动提醒你家里没有人，其他团队会提醒你家里有人。
> 
> 这被认为是作弊。
My friend wrote that this function will automatically alarm only when others are 5 bars away from the bed, I think this function is very practical, but later he did not update this function can not work, I think the author can consider adding such a function, "free trap tips".

**Comment by unparted** [comment]
> > > > > 是的，但是您仍然可以在旧版本的 mod 中输入不同的 API 密钥吗？
> > > > 
> > > > 
> > > > 是的，这是当前的解决方案，直到我制作一个新版本，该版本增加了仍然使用旧系统的能力 我在游戏开始时有一个新想法，根据他们自己的资源池检测 30 个方格半径内的所有玩家。当这个范围内没有队友时，它会自动提醒你家里没有人，其他团队会提醒你家里有人。
> > 
> > 
> > 这被认为是作弊。
> > My friend wrote that this function will automatically alarm only when others are 5 bars away from the bed, I think this function is very practical, but later he did not update this function can not work, I think the author can consider adding such a function, "free trap tips".

too close too a cheat imo. something unlike a notification from chat which the server actually sends to the client is legit, its better.

**Comment by mengzhu3261** [comment]
> 但我认为它仍然是作弊的，因为它提供了类似于 ESP 的意识优势
This understanding is not wrong, everyone understands different, I think this does not belong to the real cheating, just provide extra convenience to me, the previous pingtab MOD can see stealth players, and now there are many people use this MOD again

**Comment by mengzhu3261** [comment]
This understanding is not wrong, everyone understands different, I think this does not belong to the real cheating, just provide extra convenience to me, the previous pingtab MOD can see stealth players, and now there are many people use this MOD again

**Comment by unparted** [comment]
Yea but in hypixel's idea of a cheat that would be considered one.

**Comment by mengzhu3261** [comment]
> 是的，但在 Hypixel 的作弊想法中，这将被视为作弊。如果这对你来说是一件大事，那么我建议你每次离开基地时都检查基地。
Okay bro, maybe you are right, but I think the idea is great, I will find someone else to implement this feature, I think this feature is really cool, although it may not be allowed by hyp

**Comment by CalMWolfs** [comment]
@unparted so ive added the death notifications, I had a look at the time since death and its definitely possible I'm just a bit short on time right now so that will have to wait a bit, you can try out the death notifications in the latest prerelease

**Comment by unparted** [comment]
Thanks Cal, you do not need to add the time since death (unless you want to of course), the death notification should be enough, thanks! I will test right now.

**Comment by unparted** [comment]
Ight, I tested it out and the old api system integration works well. Unfortunately, the death notification seems to only work for myself. When i die it works, but not for my teammates. Also the death notifications and the team kill notifications both show when death notifis are on and team notifs are off. It seems to work when team and death notifs are toggled at the same time. But i would like to just see team death notifcations. Can you do this?

**Comment by unparted** [comment]
if anything isnt clear, please ask. I was typing that while testing.

**Comment by unparted** [comment]
Also notifications work when they are all disabled.

**Comment by CalMWolfs** [comment]
Oh, I see the issue, version 0.1.6.Pre.2 should fix this but let me know if it doesnt

**Comment by mengzhu3261** [comment]
> 哦，我看到了这个问题，版本 0.1.6.Pre.2 应该解决这个问题，但如果没有，请告诉我

Author, do you have time now, some of my mods have some problems, I sent you the crash log, can you help me to see what causes it

**Comment by unparted** [comment]
> > 哦，我看到了这个问题，版本 0.1.6.Pre.2 应该解决这个问题，但如果没有，请告诉我
> 
> Author, do you have time now, some of my mods have some problems, I sent you the crash log, can you help me to see what causes it

What is your discord I will try to help you.

**Comment by unparted** [comment]
@CalMWolfs the notifications still don't show when death notifs are toggled on only, I have to toggle team and death notifs for it to the death notifs to work. Also when I disable all notifs they actually disable now which is good, thanks.

**Comment by CalMWolfs** [comment]
> @CalMWolfs the notifications still don't show when death notifs are toggled on only, I have to toggle team and death notifs for it to the death notifs to work. Also when I disable all notifs they actually disable now which is good, thanks.

oh yes i see, another small typo on my end :sob: ill release one last version and hopefully this fixes it, very sorry

**Comment by mengzhu3261** [comment]
> > > 哦，我看到了这个问题，版本 0.1.6.Pre.2 应该解决这个问题，但如果没有，请告诉我
> > 
> > 
> > 作者，你现在有时间吗，我的一些模组有一些问题，我把崩溃日志发给你了，你能帮我看看是什么原因造成的吗
> 
> 你的不和谐是什么，我会尽力帮助你。你有不和谐吗？

my dis id is mengzhuchina help me pls

**Comment by unparted** [comment]
> oh yes i see, another small typo on my end 😭 ill release one last version and hopefully this fixes it, very sorry

awesome thanks

**Comment by unparted** [comment]
> mengzhuchina

did you spell it wrong? It says there is no user

**Comment by mengzhu3261** [comment]
> > 梦竹中国
> 
> 你拼错了吗？它说没有用户

mengzhu_china
sry

**Comment by unparted** [comment]
Hey Cal, just wanted to let you know it works now, and its awesome. Thank you so much.
